### ISSUE TITLE
Roadmap for pool support?

### ISSUE THREAD

**Issue by jimkoen** [ChainGreenOrg/chaingreen-blockchain#14]
Hello, I'd like to inquire when pool support is planned, I'm afraid that large farmers will take over the blockchain with a 51% attack.
Any replies are appreciated.

**Comment by miosukakura** [comment]
Hello @jimkoen we are following the development which is happening to Chia and working on improvements for both projects. As soon as Chia has a pool, it will be implemented on our side as well. Thank you.
