### ISSUE TITLE
Periodic Syncing Issue 

### ISSUE THREAD

**Issue by decisev** [ChainGreenOrg/chaingreen-blockchain#20]
**Describe the bug**
Chaingreen client will go into a "Syncing but still Connected" mode for a few minutes, happens randomly and the block height it syncs to appears randomly. Lasts approximately 1-2 minutes before syncing back to normal.

**To Reproduce**

-Open Chaingreen client
-Wait random amount of time
-Observe that the client will go into Syncing mode with a block height far beyond the current block

**Image of issue for clarification**
![syncingissue (2)](https://user-images.githubusercontent.com/77240399/121666425-3db31e80-ca77-11eb-9bee-087819782176.png)

**Expected Results**
Sync should be complete and normally following the blockchain progress

**Comment by miosukakura** [comment]
@decisev check that issue - https://github.com/ChainGreenOrg/chaingreen-blockchain/issues/17 . The PRs that are fixing it are #18 and #19

**Comment by decisev** [comment]
I did not realize this issue was due to the cause of chia peers connecting. I will eliminate the peers with chia port and continue to wait the PR for fix. Thank you
