### ISSUE TITLE
[BUG] High latency when fetching plots from an HDD

### ISSUE THREAD

**Issue by miosukakura** [ChainGreenOrg/chaingreen-blockchain#21]
**Describe the bug**
It seems that some users are having an issue with higher than 5s latency on HDDs that store the plots. 

**To Reproduce**

1. Open both Chia and Chaingreen
2. Start farming
3. Observe the issue in the logs.

**Expected behavior**
This not to happen

## Please use the following format for the comments about your system configs
**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]
- HDDs: 
- Number of plots
- Connection to the plots

**Additional context**

**Comment by Fuzzydroid** [comment]
OS: Windows 10 Pro N (20H2)
CPU: i5-10400
HDD: 4x8TB external, 2x8TB internal and an Unraid share.
Plots: 553
Connection: Via Unraid.

Both the externals and internals are connected to the Unraid server, but are not a part of the array. The share obviously is part of the array. The OS is running in a VM on Unraid. The vast majority of my checks are above 5 seconds causing the warning.

When I run this on my PC and access the same drives as network shares, it has 0 warning. My PC specs:

OS: Windows 10 Pro (20H2)
CPU: Ryzen 9 5900X
HDD: 4x8TB external, 2x8TB internal and an Unraid share.
Plots: 553
Connection: Via network shares from an Unraid server.

**Comment by RAG3XXX** [comment]
OS : Windows 10
OS Version : 19042.1052
CPU : AMD Ryzen 7 2700X Eight-Core Processor            3.70 GHz
HDD : 1x 4TB Internal
           2x 2TB Internal
           8x 1TB External
Plots : 138
Connection : Internal & External

No issues when I have the Chia client open my time is below 1 sec with the same setup
Also hpool client reports below 1 sec as well

**Comment by miosukakura** [comment]
Do you still have that issue considering that the difficulty has increased?

**Comment by RAG3XXX** [comment]
Looks a lot better now thank you

Getting lookup times in the milliseconds

**Comment by miosukakura** [comment]
I'm closing the issue as it doesn't occur anymore. Please reopen if it happens again.
