### ISSUE TITLE
[BUG] Netspace showing vastly lower number than correct 

### ISSUE THREAD

**Issue by ab212121** [ChainGreenOrg/chaingreen-blockchain#24]
**Describe the bug**
On installing 1.16 fresh, network is synced to latest block and up to date but showing netspace as 1.536mib only when current netspace is in pib 

**To Reproduce**

Fresh install

**Expected behavior**
Expect netspace to show correct current network storage space

**Screenshots**
![image](https://user-images.githubusercontent.com/85769211/121754496-11e67600-cb15-11eb-8960-b7833f5e016a.png)

**Desktop (please complete the following information):**

- OS: Windows 10 x64
- CPU: Intel Core i7 10700KF

**Comment by miosukakura** [comment]
@ab212121 the issue doesn't occur anymore so I'm closing the issue.
