### ISSUE TITLE
[BUG] Timelords overloaded because of extremelly fast network growth

### ISSUE THREAD

**Issue by miosukakura** [ChainGreenOrg/chaingreen-blockchain#25]
**Describe the bug**
Because of the very fast network growth the difficulty is not adjusting as fast as it should be and the timelords are overloaded.

**Proposed solution**
Change the initial difficulty to match Chia initial difficulty and activate that rule on block 200000 via hard fork (potentially should happen in June 18).

Please vote using the :+1: and :-1:

**Comment by privacybtc** [comment]
👍

**Comment by MadDogMayCry0** [comment]
pls don't ask users any questions... Just DO IT! :D

**Comment by SparXalt** [comment]
The chain is running better day by day, It may be that hardforking in unneeded. I need run some more some numbers but I propose pushing this out a little farther than block 200k to see if it can start to right itself.

**Comment by miosukakura** [comment]
Things are getting better and I don't think that it will be needed at all. I'm closing this issue and if there is a problem again, I will reopen it.
