### ISSUE TITLE
[BUG] - Webpage design

### ISSUE THREAD

**Issue by MadDogMayCry0** [ChainGreenOrg/chaingreen-blockchain#26]
**Describe the bug**
Webpage design

**To Reproduce**
Open the site and look at it 

**Expected behavior**
Tasteful design 

**Additional context**
Need professional work. Write me ctacb@mail.ru to fix it for free.

**Comment by miosukakura** [comment]
As an open source non-profit project we do really appreciate non-profit work from our contributers. Please let us know if you are going to contribute for that and we will be happy to meet you.

**Comment by MadDogMayCry0** [comment]
Let you know that I am glad to contribute :) If the feedback form on the site works, then I will send my suggestions there.

**Comment by miosukakura** [comment]
Yes, but we are not Chia, we are chaingreen. Moreover Chia can be registered as a trademark and therefore we can be sued. Let's continue the discussion in Discord or on email, but I will close the issue here.
