### ISSUE TITLE
unable to install gui on unbuntu server

### ISSUE THREAD

**Issue by nickdanino** [ChainGreenOrg/chaingreen-blockchain#29]
received the following error when trying to install the gui on ubuntu server. 

apt-get is /usr/bin/apt-get
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxss1 is already the newest version (1:1.2.3-1).
nodejs is already the newest version (10.19.0~dfsg-3ubuntu1).
npm is already the newest version (6.14.4+ds-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Installing on Ubuntu 20.04 LTS or newer: Using installed node.js version.
Running git submodule update --init --recursive.

Submodule 'chaingreen-blockchain-gui' (git@github.com:ChainGreenOrg/chaingreen-blockchain-gui.git) registered for path 'chaingreen-blockchain-gui'
Cloning into '/home/xxxxx/chaingreen-blockchain/chaingreen-blockchain-gui'...
Warning: Permanently added the RSA host key for IP address 'xxx.xx.xxx.x' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ChainGreenOrg/chaingreen-blockchain-gui.git' into submodule path '/home/xxxxx/chaingreen-blockchain/chaingreen-blockchain-gui' failed
Failed to clone 'chaingreen-blockchain-gui'. Retry scheduled
Cloning into '/home/xxxxxxxchaingreen-blockchain/chaingreen-blockchain-gui'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ChainGreenOrg/chaingreen-blockchain-gui.git' into submodule path '/home/xxxxxxx/chaingreen-blockchain/chaingreen-blockchain-gui' failed
Failed to clone 'chaingreen-blockchain-gui' a second time, aborting

**Comment by miosukakura** [comment]
This will be resolved by the next update.

**Comment by miosukakura** [comment]
Duplicates #23 so I will close the issue. Follow the other topic.
