### ISSUE TITLE
How can I get the compiled version 1.2.0?

### ISSUE THREAD

**Issue by SergeyKGoncharov** [ChainGreenOrg/chaingreen-blockchain#34]
How can I get the compiled version (*. exe) to install on Windows?

**Comment by DmitryYamen** [comment]
How about Mac OS?

**Comment by antropovp** [comment]
https://github.com/ChainGreenOrg/chaingreen-blockchain/releases/download/1.2.0/ChaingreenSetup-1.2.0.exe

**Comment by automation13** [comment]
> How can I get the compiled version (*. exe) to install on Windows?

Don't install this app, its scam. Literally copy/paste from original chia repo with minor changes....

**Comment by SergeyKGoncharov** [comment]
> https://github.com/ChainGreenOrg/chaingreen-blockchain/releases/download/1.2.0/ChaingreenSetup-1.2.0.exe
> 
> https://github.com/ChainGreenOrg/chaingreen-blockchain/releases



> > How can I get the compiled version (*. exe) to install on Windows?
> 
> Don't install this app, its scam. Literally copy/paste from original chia repo with minor changes....

Chia scam. Chaingreen is good

**Comment by miosukakura** [comment]
@SergeyKGoncharov if everything is clear feel free to close the issue. Thanks for the support of the project!

**Comment by miosukakura** [comment]
@antropovp Спасибо!
