### ISSUE TITLE
Version 1.2.0 is almost always in Sync status or no sync

### ISSUE THREAD

**Issue by SergeyKGoncharov** [ChainGreenOrg/chaingreen-blockchain#36]
Version 1.2.0 is almost always in Sync status or no sync. Will this be fixed or is it better to go back to the previous version?

**Comment by KnoeperKalle** [comment]
Same here. Syncs slower, than the chain moves forward... block 174214/177315 right now

**Comment by SergeyKGoncharov** [comment]
When I start the application, an error appears and I have lost all the coins
![Error](https://user-images.githubusercontent.com/84588771/122571236-2d8dd700-d055-11eb-877f-6d4d15d6ee9c.PNG)
![Error1](https://user-images.githubusercontent.com/84588771/122571239-2e266d80-d055-11eb-9a51-fe2a5c4f170f.PNG)

**Comment by nickdanino** [comment]
I am in the same boat always syncing or I'm getting the message saying not synced.  I have only been synced for a few minutes since updating to 1.2.0

**Comment by miosukakura** [comment]
It's a complex problem because the timelords are a bit slow for that dfficulty. We did setup an 80 core machine with 128 GB RAM and after it's synched it should improve a lot.

**Comment by SergeyKGoncharov** [comment]
miosukakura, thank you for your response, but still no syncing. I installed the previous version of the app, but it also doesn't sync. I lost 22,000 coins. How can I get them back?
<img width="906" alt="error" src="https://user-images.githubusercontent.com/84588771/122631798-08da4380-d0d7-11eb-927f-7744b6c007b2.PNG">

**Comment by miosukakura** [comment]
@SergeyKGoncharov can you check now? Our nodes has been fully synched in the last 41 hours.

**Comment by gyarros** [comment]
Hi, about 1 hour ago I installed 1.2.0 and it does not sync

**Comment by gyarros** [comment]
can you pass me some peers to see if I can sync. Thank you.

**Comment by djjaeger82** [comment]
Is this project abandoned?  I just learned about it today but seems like nothing will sync with 1.2.0

**Comment by pwagma** [comment]
im having same issue, no connections

**Comment by anilsanwal54** [comment]
Guys I am telling you node address with their port no. . The issue will connecting issue will resolve
220.133.72.31 : 8744
175.43.35.20 : 8744
108.29.36.86 : 8744
46.189.74.40 : 8744
167.114.115.202 : 8744

**Comment by SergeyKGoncharov** [comment]
> @SergeyKGoncharov can you check now? Our nodes has been fully synched in the last 41 hours.

I completely reinstalled the app with the removal of all directories and the synchronization now works and there is farming. The coins I received earlier were returned to me. However, the coins are not displayed on the Farming tab. I can only see them on the Wallet tab

**Comment by KnoeperKalle** [comment]
> 's synched it should improve a lot.

That helped. Always Synced now.

**Comment by anilsanwal54** [comment]
Try these :-

220.133.72.31 : 8744
175.43.35.20 : 8744
108.29.36.86 : 8744
46.189.74.40 : 8744
167.114.115.202 : 8744

**Comment by miosukakura** [comment]
Closing the issue
