### ISSUE TITLE
ERROR `>` not supported between instances of `NoneType1 and `uind32`

### ISSUE THREAD

**Issue by SergeyKGoncharov** [ChainGreenOrg/chaingreen-blockchain#39]
When this error is fixed. The third day the app is not syncing

**Comment by nflows** [comment]
I think this project seems to be scam or idk... Nothing developed within this week. Horrible Fork

**Comment by miosukakura** [comment]
@SergeyKGoncharov We will check what is going on. The same thing happening on one of our machines. 
@nflows check the github activity and let's talk then.

**Comment by miosukakura** [comment]
This is a duplicate of #38 so I am closing the issue.
