### ISSUE TITLE
[BUG] windows installer broken zip

### ISSUE THREAD

**Issue by dymax22** [ChainGreenOrg/chaingreen-blockchain#67]
windows installer  - broken zip

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by miosukakura** [comment]
@dymax22 please download the installer.exe file from the release.
