### ISSUE TITLE
[BUG]1.2.1 windows installer.zip,  data error can't install on this windows.  I have windows 10?

### ISSUE THREAD

**Issue by PC101guy** [ChainGreenOrg/chaingreen-blockchain#69]
I extracted it, but it shows data error? tried multiple times.   anyone have any luck?

**Comment by jhovannyLinares** [comment]
Mismo error, descargue varias veces y pasa lo mismo.

**Comment by g4m34x** [comment]
Same here. The zip is corrupted on the server. Tried to download it multiple times with multiple browsers.

**Comment by Satheeshks3** [comment]
same here file seems to be corrupted . PLZ UPDATE

**Comment by uar-mikhail-markelov** [comment]
zip file is broken

**Comment by Jared-woodruff** [comment]
Yes the zip file is broken

**Comment by marcelo74mayo** [comment]
error zip file dosnt descompres windows 10

**Comment by q246121410** [comment]
is there any one build a windows 10 installer instead?

**Comment by miosukakura** [comment]
I have added the installer.exe to be available in the release instead of the zip.
